### PR TITLE
Resolve #2, vulnerability in old Mocha version

### LINKED ISSUE #2: Vulnerability in old Mocha
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ mocha [dev]                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ mocha > glob > minimatch                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/118                       │
└───────────────┴──────────────────────────────────────────────────────────────┘



```

### PR DESCRIPTION
**Pull request by ain**

### CODE REVIEW

**Comment by doowb** [comment]
Thanks @ain. Please remove the `package-lock.json` file and this LGTM.

**Comment by ain** [comment]
@doowb is there a particular reason you don't want the lock file around? I think Github's security check against CVE list works based on the lock files, e.g. `Gemfile.lock`, `package-lock.json`.

**Comment by doowb** [comment]
Our convention has been to exclude lock files from the repositories.

Thanks again for the PR!

**Comment by mojoaxel** [comment]
> Our convention has been to exclude lock files from the repositories.

Due to [npm's docs](https://github.com/npm/npm/blob/v5.0.0/doc/files/package-lock.json.md) this file should be committed.

**Comment by ain** [comment]
Coming with Rails experience, I also think lock files do deliver additional value despite the occasional merging issues that can be resolved easily. Maybe something that deserves a 2nd look into it.

**Comment by doowb** [comment]
> One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package.

I believe that this key detail makes it pointless to have a `package-lock.json` file in a package like this.

> Maybe something that deserves a 2nd look into it.

Since it's a convention, I think there may be some exceptions (for example, when working on an internal web/server project with a team that has agreed to use `npm`), but in this case, the `package-lock.json` isn't necessary.

**Comment by jonschlinkert** [comment]
> Due to npm's docs this file should be committed.

If you need determinism in a library that consumes this one, then you can achieve that without this library having a lockfile, by using a lockfile in your own library. This is a micro-lib with one dependency.  A lockfile in this library would be focused mainly on guaranteeing deterministic installs for `devDependencies`, which IMHO is completely useless and would likely cause more issues and frustration than potential benefits. Especially since it prevents semantic versioning from working the way it's intended. For example, patches for vulnerabilities, like the one this issue was created about wouldn't be automatically used anymore, as just upgrading patches requires manual intervention.  

> I also think lock files do deliver additional value despite the occasional merging issues that can be resolved easily

From my perspective, lockfiles have been nothing short of a nightmare to date, for both NPM and yarn.  We've had a number of issues that were solved by having developers delete their lockfiles before re-installing everything. But we have never had a single issue that could have been prevented by a lockfile.

At some point in the future, when lockfiles are as good as the promises they make, we'll take another look.

**Comment by ain** [comment]
Understood. Thanks for elaborating on the topic and disclosing your view.

**Pull request merged**
